### PR TITLE
docs(user-guide) Add Keycloak documentation and substantially refactor for better layout

### PR DESCRIPTION
**Pull request by msavy**

### CODE REVIEW

**Comment by EricWittmann** [comment]
Sadly the documentation now fails to render. :(

```
[ERROR] Failed to execute goal org.jboss.maven.plugins:maven-jdocbook-plugin:2.3.9:generate (default-generate) on project apiman-guides-user-guide: XSLT problem: error rendering [org.apache.fop.fo.ValidationException: "fo:table" is missing child elements. Required content model: (marker*,table-column*,table-header?,table-footer?,table-body+) (See position -1:-1); SystemID: jar:file:/C:/Users/Eric/.m2/repository/net/sf/docbook/docbook-xsl-ns/1.74.0/docbook-xsl-ns-1.74.0.jar!/fo/formal.xsl; Line#: 515; Column#: -1] on Guide.xml -> [Help 1]
```

**Comment by msavy** [comment]
It seems to fail before this commit.

**Comment by msavy** [comment]
I’ve tracked it down - it’s caused by 4a097c7 (Len’s Crash Course)

**Comment by EricWittmann** [comment]
Ah OK sorry.  Notifying @ldimaggi ! :)

**Comment by msavy** [comment]
I’ve started correcting it, but there’s quite a few more changes needed than I expected.

I also found a few areas where I think someone intended to come back and finish a sentence but probably forgot (stops mid-sentence). I’ll put some pointers on them shortly.

**Comment by msavy** [comment]
@EricWittmann @ldimaggi I've fixed it up so it builds successfully (see https://github.com/apiman/apiman-guides/pull/25) - I took a few liberties with translating stuff from markdown to asciidoc, so if it's not to your liking I won't be offended if you change things around.

**Comment by ldimaggi** [comment]
I am seldom offended.    ;-)

It seems to be inlcuded in the user guide?
http://www.apiman.io/latest/user-guide.html

Is this right?


-- Len



On Sun, May 1, 2016 at 7:48 PM, Marc Savy <notifications@github.com> wrote:

> @EricWittmann <https://github.com/EricWittmann> @ldimaggi
> <https://github.com/ldimaggi> I've fixed it up so it builds successfully
> (see #25 <https://github.com/apiman/apiman-guides/pull/25>) - I took a
> few liberties with translating stuff from markdown to asciidoc, so if it's
> not to your liking I won't be offended if you change things around.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/apiman/apiman-guides/pull/20#issuecomment-216082250>
>



-- 
Len DiMaggio (ldimaggi@redhat.com)
JBoss by Red Hat
314 Littleton Road
Westford, MA 01886  USA
tel:  978.392.3179
cell: 781.472.9912
http://www.redhat.com
http://community.jboss.org/people/ldimaggio

**Comment by msavy** [comment]
IMO, it should have its own page: it’s way too long and slightly confusing otherwise.

**Comment by EricWittmann** [comment]
Agreed -  that was my plan. :)

**Pull request merged**
